version: "3"

services:
  web:
    build:
      dockerfile: ./Dockerfile
      args:
        YOUR_ENV: development
        POETRY_VERSION: 1.1.12
    depends_on:
      - "db"

  db:
    image: postgres:14.2-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    depends_on:
      - "web"

volumes:
  db-data:
