version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./staticfiles:/app_staticfiles
      - ./media:/app_media
    ports:
      - "5000:8000"
    env_file:
      - ./.env.dev
  db:
    env_file:
      - ./.env.db.dev
    ports:
      - "5432:5432"

  caddy:
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./CaddyfileDev:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./staticfiles:/app_staticfiles
      - ./media:/app_media

volumes:
  db-data: