version: "3"
services:
  web:
    build: .
    command: gunicorn bookmarks.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  db:
    image: postgres:14.2-alpine
    env_file:
      - ./.env.db.prod
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data

  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./app/staticfiles:/app/staticfiles
      - ./app/media:/app/media

volumes:
  db-data: