# Generated by Django 4.0.3 on 2022-04-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19),
        ),
    ]
